"""
Generate every LaTeX table in the thesis directly from the pipelines' own CSV outputs.

No figure in this thesis is typed by hand. Each table below is written from the CSV that
the corresponding pipeline produced, so a rerun that changes a result changes the thesis
on the next invocation of this script, not leaving a stale number behind.

This is the same guarantee tools/verify_docs.py enforces for the README, extended to the
dissertation itself. Section 2.1 of the University of Verona thesis regulation scores
"accuratezza dello svolgimento e della scrittura"; a transcription error in a results
table is the most avoidable way to lose that point.

Usage:  python Thesis/tools/make_tables.py
"""

import re
import csv
import io
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(ROOT, "Thesis", "tables")

DOMAINS = [("robotic", "Robotics (Pepper)"), ("healthcare", "Healthcare (PTB-XL)"),
           ("industrial", "Industrial (TEP)")]
ALGOS = [("PCMCI", "PCMCI"), ("GES", "GES"), ("CAM-UV", "CAM-UV")]
VARIANTS = ["Linear / Ridge", "Polynomial degree 3", "RBF + Ridge"]
VSHORT = {"Linear / Ridge": "Linear", "Polynomial degree 3": "Poly-3", "RBF + Ridge": "RBF"}

def bold_best(rows, cols, lower=()):
    """Bold the best value in each named column, across one block of rows.

    rows is a list of cell-lists, all the same width; cols is the indices to treat
    as performance metrics. Non-numeric cells ("--") are skipped. Ties are all
    bolded, which is the honest rendering -- suppressing one would imply a winner
    the numbers do not give.

    Columns listed in lower are the ones where small is good -- false positives,
    false negatives, seconds. Bolding the maximum there would mark the worst cell
    in the table as the best one, so the direction has to be carried per column
    and not assumed.
    """
    for c in cols:
        vals = []
        for r in rows:
            try:
                vals.append(float(r[c]))
            except (ValueError, IndexError):
                vals.append(None)
        live = [v for v in vals if v is not None]
        if not live:
            continue
        top = min(live) if c in lower else max(live)
        for r, v in zip(rows, vals):
            if v is not None and v == top:
                r[c] = BF + r[c] + "}"
    return rows


def fault_label(name):
    """Render a fault identifier as prose, not as the filename it came from.

    The CSVs carry "Attack_1" and "Fault_17" because that is what the directories
    are called. Escaped through esc() they reach the page as Attack\_1, which sets
    a visible underscore in a body-text column and reads as a variable name rather
    than as the name of a fault. The robotics classes (WheelsControl and the rest)
    carry no underscore and pass through untouched.
    """
    return str(name).replace("_", " ")


MULTIROW = "\\multirow{3}{*}{"
BF = "\\textbf{"
BFM = "\\mathbf{"   # bold inside math mode; \textbf does not bold mathematical output
NL = " \\\\"


def folder(algo, dom):
    """Map an (algorithm, domain) pair to its results directory."""
    if algo == "PCMCI":
        return "PCMCI/PCMCI_" + dom
    if algo == "GES":
        return "GES/GES_" + dom
    return "CAM-UV/CAM_UV_" + ("robotics" if dom == "robotic" else dom)


def read(path):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return []
    return list(csv.DictReader(io.open(p, encoding="utf-8")))


def esc(s):
    """Escape the LaTeX specials that appear in sensor names."""
    return str(s).replace("_", "\\_").replace("&", "\\&").replace("%", "\\%")


def write(name, lines):
    path = os.path.join(OUT, name)
    header = ("% GENERATED by Thesis/tools/make_tables.py -- do not edit by hand.\n"
              "% Every figure below is read from a CSV written by the pipelines.\n")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + "\n".join(lines) + "\n")
    print("  " + name)


def cap_open(text):
    """The opening of a caption, carrying a short form when the text needs one.

    Every table goes through this, floats and longtables alike: a longtable sets its
    caption and label on one line and so cannot use caption() below, and writing the
    short form into the generated file instead loses it on the next run."""
    short = _first_sentence(text)
    return "\\caption[" + short + "]{" if short else "\\caption{"


def caption(text, label):
    """A caption explains why a table should not be misread, which belongs under
    the table and not in the list of tables. Without a short form the whole
    paragraph prints in both, so the list gets the first sentence."""
    return [cap_open(text) + text + "}", "\\label{" + label + "}"]


def _first_sentence(text):
    t = " ".join(text.split())
    if len(t) < 120:
        return None
    for m in re.finditer(r"(?<![0-9])[.] ", t):
        cand = t[:m.start()]
        if not _balanced(cand):
            continue
        if 15 < len(cand) <= 150:
            return cand
        return _clause(cand)
    return None


def _clause(sentence):
    """A first sentence too long for the list of tables, cut back to its last clause
    boundary. The opening clause names the table; what follows it qualifies."""
    cut = None
    for m in re.finditer(r", ", sentence):
        if 15 < m.start() <= 150 and _balanced(sentence[:m.start()]):
            cut = m.start()
    return sentence[:cut] if cut else None


def _balanced(s):
    return s.count("{") == s.count("}")


def sci(v):
    """Render a CSV value, promoting exponent notation to proper LaTeX mathematics."""
    s = str(v).strip()
    if "e" in s.lower():
        mant, exp = s.lower().split("e")
        return "$" + mant + " \\times 10^{" + str(int(exp)) + "}$"
    return s


# ----------------------------------------------------------------- main results
def t_main():
    """The headline table: 27 configurations, AUC-ROC, grouped by domain."""
    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Detection performance (AUC-ROC) for all 27 causal configurations. Rows are causal "
        "discovery algorithms, columns are regression variants, blocks are application "
        "domains. The best value within each domain is shown in bold.",
        "tab:main-results")
    lines += ["\\begin{tabular}{llrrr}", "\\toprule",
              "Domain & Algorithm & Linear / Ridge $\\uparrow$ & Polynomial $\\uparrow$ & RBF + Ridge $\\uparrow$" + NL,
              "\\midrule"]
    for di, (dom, dlabel) in enumerate(DOMAINS):
        allv = []
        for algo, _ in ALGOS:
            rows = {r["Model Variant"]: r for r in read(folder(algo, dom) + "/outputs/metrics_summary.csv")}
            allv += [float(rows[v]["AUC_ROC"]) for v in VARIANTS if v in rows]
        best = max(allv) if allv else None
        for ai, (algo, alabel) in enumerate(ALGOS):
            rows = {r["Model Variant"]: r for r in read(folder(algo, dom) + "/outputs/metrics_summary.csv")}
            cells = []
            for v in VARIANTS:
                if v not in rows:
                    cells.append("--")
                    continue
                x = float(rows[v]["AUC_ROC"])
                cells.append((BF + "%.4f" % x + "}") if x == best else "%.4f" % x)
            dcell = (MULTIROW + dlabel + "}") if ai == 0 else ""
            lines.append(dcell + " & " + alabel + " & " + " & ".join(cells) + NL)
        if di < len(DOMAINS) - 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_main_results.tex", lines)


# ------------------------------------------------------------ per-domain detail
def t_domain_detail():
    """One full confusion-matrix table per domain: every metric, all nine configurations."""
    for dom, dlabel in DOMAINS:
        short = dlabel.split(" (")[0].lower()
        lines = ["\\begin{table}[htbp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{3pt}"]
        lines += caption(
            "Complete detection metrics for the " + short + " domain. The threshold is the "
            "95th percentile of the fault-free score distribution, computed without reference "
            "to any anomaly label.",
            "tab:detail-" + dom)
        lines += ["\\begin{tabular}{llrrrrrrrrrr}", "\\toprule",
                  "Algorithm & Variant & Thr. & TP $\\uparrow$ & FP $\\downarrow$ & TN $\\uparrow$ & FN $\\downarrow$ & Acc. $\\uparrow$ & Prec. $\\uparrow$ & Rec. $\\uparrow$ & F1 $\\uparrow$ & AUC $\\uparrow$" + NL,
                  "\\midrule"]
        # Bolding is computed over all nine rows at once and only then split back into
        # the per-algorithm blocks.
        block, acells = [], []
        for ai, (algo, alabel) in enumerate(ALGOS):
            rows = {r["Model Variant"]: r for r in read(folder(algo, dom) + "/outputs/metrics_summary.csv")}
            for vi, v in enumerate(VARIANTS):
                if v not in rows:
                    continue
                r = rows[v]
                acells.append(((MULTIROW + alabel + "}") if vi == 0 else "", ai))
                block.append([VSHORT[v], "%.3f" % float(r["Threshold"]), r["TP"], r["FP"],
                              r["TN"], r["FN"], r["Accuracy"], r["Precision"], r["Recall"],
                              r["F1"], r["AUC_ROC"]])
        # Only the rate columns are bolded, and the confusion counts deliberately are
        # not. The nine rows do not share a denominator: PCMCI subsamples at its own
        # rate, so on robotics it scores 181 observations where GES and CAM-UV score
        # 1378. Bolding the raw counts would hand PCMCI "fewest false positives" for
        # having scored seven times fewer samples, which is the exact confusion
        # Section~\\ref{sec:method-preprocessing} declares as this study's principal
        # threat to internal validity. A rate is comparable across denominators; a
        # count is not. Threshold is a setting rather than a score and is left alone.
        bold_best(block, [6, 7, 8, 9, 10])
        last_ai = None
        for (acell, ai), cells in zip(acells, block):
            if last_ai is not None and ai != last_ai:
                lines.append("\\midrule")
            lines.append(acell + " & " + " & ".join(str(c) for c in cells) + NL)
            last_ai = ai
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
        write("tbl_detail_" + dom + ".tex", lines)


# ---------------------------------------------------------------------- baselines
def dmatch(v, dom):
    """Match a Dataset cell against a domain key, across the labels used in the CSVs."""
    v = str(v).lower()
    return ((dom in v)
            or (dom == "robotic" and "pepper" in v)
            or (dom == "healthcare" and ("ecg" in v or "ptb" in v))
            or (dom == "industrial" and "tep" in v))


def best_causal(dom):
    """Highest AUC-ROC over the nine causal configurations in a domain."""
    vals = []
    for algo, _ in ALGOS:
        for r in read(folder(algo, dom) + "/outputs/metrics_summary.csv"):
            vals.append(float(r["AUC_ROC"]))
    return max(vals) if vals else None


def t_baselines():
    """Neural and parameter-free baselines against the best causal configuration.

    The neural rows are means over three seeds; the standard deviation is carried into the
    table because a difference smaller than it is not a difference. The architecture is in
    the Variant column -- Model is constant at "Neural Baseline" -- so the row label is
    taken from Variant.
    """
    # The tuned file is preferred wherever it exists. Both sets of numbers are produced by
    # the same script; the difference is that the tuned run searches the twelve-configuration
    # grid on every domain, where the earlier run searched only robotics and gave healthcare
    # and industrial a single fixed configuration. Comparing a tuned causal pipeline against
    # an untuned neural one is the specific criticism this thesis makes of the literature,
    # so it must not appear in this thesis's own baseline table.
    neural = (read("Baselines/outputs/neural_all_domains_tuned.csv")
              or read("Baselines/outputs/neural_all_domains.csv"))
    trivial = read("Baselines/outputs/trivial_baseline.csv")
    if not neural:
        print("  (skipped baselines: no neural_all_domains CSV present)")
        return

    archs = []
    for r in neural:
        if r["Variant"] not in archs:
            archs.append(r["Variant"])

    # Assemble the whole table as values first, so the column maximum can be marked
    # honestly. Bolding the best causal row regardless of the column would hide the
    # industrial result, which is the one the discussion has to confront.
    body = []
    for a in archs:
        vals = []
        for dom, _ in DOMAINS:
            m = [r for r in neural if r["Variant"] == a and dmatch(r["Dataset"], dom)]
            vals.append((float(m[0]["AUC_ROC"]), float(m[0]["AUC_std"])) if m else None)
        body.append((esc(a.replace(" Autoencoder", "")) + " autoencoder", vals, False))
    if trivial:
        vals = []
        for dom, _ in DOMAINS:
            m = [r for r in trivial if dmatch(r["Dataset"], dom)]
            vals.append((float(m[0]["AUC_ROC"]), None) if m else None)
        body.append(("Trivial control, mean $|z|$", vals, True))
    vals = []
    for dom, _ in DOMAINS:
        b = best_causal(dom)
        vals.append((b, None) if b is not None else None)
    body.append(("Best causal configuration", vals, True))

    col_max = []
    for i in range(len(DOMAINS)):
        seen = [v[i][0] for _, v, _ in body if v[i] is not None]
        col_max.append(max(seen) if seen else None)

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Non-causal reference points, as AUC-ROC. The neural autoencoders read the same "
        "variables and apply the same 95th-percentile fault-free threshold as the causal "
        "pipelines, and are reported as the mean over three seeds with the standard "
        "deviation across them. They run at PCMCI's scoring resolution in every domain, "
        "which matches the best causal configuration on robotics and industrial but not "
        "on healthcare. Table~\\ref{tab:baseline_parity} sets out what each side "
        "was given in each domain, including the direction of that asymmetry, which runs "
        "against this thesis instead of for it. The trivial control is a parameter-free "
        "mean absolute $z$-score with no learned parameters at all. Bold marks the best "
        "value in each column, whichever family it belongs to.",
        "tab:baselines")
    lines += ["\\begin{tabular}{lccc}", "\\toprule",
              "Method & Robotics $\\uparrow$ & Healthcare $\\uparrow$ & Industrial $\\uparrow$" + NL, "\\midrule"]
    for bi, (label, vals, rule) in enumerate(body):
        if rule:
            lines.append("\\midrule")
        cells = []
        for i, v in enumerate(vals):
            if v is None:
                cells.append("--")
                continue
            mu, sd = v
            txt = "%.4f" % mu if sd is None else "%.4f \\pm %.4f" % (mu, sd)
            cells.append(("$" + BFM + txt + "}$") if mu == col_max[i] else "$" + txt + "$")
        lines.append(label + " & " + " & ".join(cells) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_baselines.tex", lines)


# -------------------------------------------------------------------- bootstrap
def t_bootstrap():
    rows = read("tools/bootstrap_intervals.csv")
    if not rows:
        print("  (skipped bootstrap: CSV absent)")
        return
    # Ten columns, three of them long strings, ran past the text block and dropped the
    # last four off the page. Dataset is redundant -- Folder already names the domain --
    # and the variant abbreviates, which brings the table inside the margin.
    # The Folder column printed the results directory verbatim -- CAM\_UV\_healthcare --
    # which is a path, not a label, and set an underscore in every one of 27 rows. The
    # folder encodes exactly two facts, so it is split into the two columns it stands for.
    FOLDER_ALGO = {"PCMCI": "PCMCI", "GES": "GES", "CAM_UV": "CAM-UV"}
    FOLDER_DOM = {"robotic": "Robotics", "robotics": "Robotics",
                  "healthcare": "Healthcare", "industrial": "Industrial"}

    def split_folder(v):
        for pre, algo in FOLDER_ALGO.items():
            if v.startswith(pre + "_"):
                return algo, FOLDER_DOM.get(v[len(pre) + 1:], v[len(pre) + 1:])
        return v, ""

    HEAD = [("Folder", "Folder"), ("Variant", "Variant"), ("AUC", "AUC $\\uparrow$"),
            ("CI_low", "CI low"), ("CI_high", "CI high"), ("n", "$n$"),
            ("block", "$L$"), ("HM_low", "HM low"), ("HM_high", "HM high")]
    present = [(key, head) for key, head in HEAD if key in rows[0]]
    print("  [bootstrap columns: " + str([h for _k, h in present]) + "]")
    align = "lll" + "r" * (len(present) - 2)
    lines = ["\\begin{table}[htbp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{3pt}"]
    lines += caption(
        "Moving-block bootstrap confidence intervals on AUC-ROC, with the analytical "
        "Hanley--McNeil (HM) interval alongside for comparison, which is what the HM low "
        "and HM high columns report. Blocks preserve the serial "
        "correlation of the score series, which an i.i.d.\\ resample would destroy and which "
        "would otherwise make every interval spuriously narrow. $L$ is the block length, "
        "derived per series as $\\max(2, \\operatorname{round}(n^{1/3}))$. The bold AUC "
        "in each algorithm-domain block is the best of the three regression variants on "
        "that data; no comparison is drawn between blocks, which score different "
        "observations.",
        "tab:bootstrap")
    heads = []
    for _k, head in present:
        heads += ["Algorithm", "Domain"] if head == "Folder" else [head]
    lines += ["\\begin{tabular}{" + align + "}", "\\toprule",
              " & ".join(heads) + NL, "\\midrule"]
    body, auc_col = [], None
    for r in rows:
        cells = []
        for key, _head in present:
            v = r.get(key, "")
            if key == "Folder":
                cells += list(split_folder(v))
            elif key == "Variant":
                cells.append(esc(VSHORT.get(v, v)))
            else:
                if key == "AUC":
                    auc_col = len(cells)
                cells.append(esc(v))
        body.append(cells)
    # Bolding runs within one algorithm-domain block and never across them. The best
    # of three regression variants on the same data is a comparison this table can
    # support; the best of 27 rows drawn from three different datasets is not.
    if auc_col is not None:
        i = 0
        while i < len(body):
            j = i
            while j < len(body) and body[j][:2] == body[i][:2]:
                j += 1
            bold_best(body[i:j], [auc_col])
            i = j
    for cells in body:
        lines.append(" & ".join(cells) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_bootstrap.tex", lines)


# ------------------------------------------------------------------- validation
def t_validation():
    rows = read("tools/algorithm_validation.csv")
    if not rows:
        print("  (skipped validation: CSV absent)")
        return
    pretty = {
        "rls_vs_ols_max_abs_diff": ("RLS at $\\lambda=1$ equals ordinary least squares",
                                    "max $|w_{\\mathrm{RLS}} - w_{\\mathrm{OLS}}|$"),
        "rls_forgetting_estimate": ("RLS with forgetting, $\\lambda = 0.995$",
                                    "estimate of a coefficient stepping to $2.5$"),
        "rls_no_forgetting_estimate": ("RLS without forgetting, $\\lambda = 1$",
                                       "same coefficient, no forgetting"),
        "drift_broken_relationship": ("Drift when the relationship breaks",
                                      "mean drift after the change"),
        "drift_rescaled_intact": ("Drift when values are rescaled but the relationship holds",
                                  "mean drift after the change"),
        "drift_unchanged": ("Drift when nothing changes", "mean drift, second half"),
    }
    # Two prose columns and a number. With plain `l` columns the prose sets its natural
    # width, the table exceeds the text block, and the Value column is pushed off the
    # page -- which is how this table shipped with its results invisible. X columns
    # divide the remaining width between the two prose columns instead.
    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Numerical validation of the detector against closed-form answers. Each row "
        "constructs a problem whose result is known independently of the implementation and "
        "confirms that the implementation reaches it.",
        "tab:validation")
    lines += ["\\begin{tabularx}{\\textwidth}{@{}Xl r@{}}", "\\toprule",
              "Check & Quantity & Value" + NL, "\\midrule"]
    for r in rows:
        q = r.get("quantity", "")
        v = str(r.get("value", ""))
        name, desc = pretty.get(q, (esc(q), ""))
        lines.append(name + " & " + desc + " & " + sci(v) + NL)
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    write("tbl_validation.tex", lines)


# ------------------------------------------------------------- confounder / power
def t_confounder():
    rows = read("CAM-UV/confounder_structure.csv")
    if rows:
        # The CSV column names are terse by design; the thesis needs them spelled out.
        cols = [("domain", "Domain"), ("d", "Variables $n$"), ("n", "Samples"),
                ("spv", "Samples/var."), ("pairs", "$|U|$"),
                ("saturation", "Saturation"), ("auc", "AUC-ROC $\\uparrow$")]
        order = {"robotics": 0, "healthcare": 1, "industrial": 2}
        rows = sorted(rows, key=lambda r: order.get(r["domain"], 9))
        lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
        lines += caption(
            "Structure recovered by CAM-UV in each domain. $P$ holds observed-parent "
            "edges and $U$ holds pairs attributed to a latent common cause. Saturation is "
            "the share of all $\\binom{n}{2}$ variable pairs appearing in $U$. The samples "
            "available per variable during discovery differ by three orders of magnitude "
            "across the three domains, which is essential context for reading the "
            "industrial row. The AUC-ROC column is the linear/ridge variant in every row, "
            "which is what makes the saturation comparison like-for-like; the placings "
            "quoted in the surrounding text are over the best variant in each domain.",
            "tab:confounder")
        lines += ["\\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", "\\toprule",
                  " & ".join(h for _, h in cols) + NL, "\\midrule"]
        for r in rows:
            cells = []
            for key, _ in cols:
                v = r.get(key, "--")
                if key == "domain":
                    cells.append(v.capitalize())
                elif key == "saturation":
                    cells.append("%.1f\\%%" % (float(v) * 100))
                elif key == "spv":
                    cells.append("%.2f" % float(v))
                else:
                    cells.append(esc(v))
            lines.append(" & ".join(cells) + NL)
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
        write("tbl_confounder.tex", lines)

    rows = read("CAM-UV/CAM_UV_industrial/tep_power_check.csv")
    if rows:
        lines = ["\\begin{table}[htbp]", "\\centering"]
        lines += caption(
            "Discovery sample-count sweep over the Tennessee Eastman training window. The "
            "graph densifies monotonically as samples grow, which identifies the sparsity "
            "seen under the evaluation protocol as absent statistical power and not a "
            "property of the process.",
            "tab:tep-power")
        lines += ["\\begin{tabular}{rrrrr}", "\\toprule",
                  "Subsample & Samples & Parent edges & Confounded pairs & Density" + NL,
                  "\\midrule"]
        for r in rows:
            d = float(r["density"]) * 100
            note = " \\footnotesize(protocol)" if r["subsample"] == "10" else ""
            lines.append(r["subsample"] + " & " + r["samples"] + note + " & "
                         + r["parent_edges"] + " & " + r["confounded"] + " & "
                         + "%.1f" % d + "\\%" + NL)
        lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
        write("tbl_tep_power.tex", lines)


# ----------------------------------------------------------------- attributions
def t_attributions():
    """Which sensor each robotics attack attributes to, against the documented requirement."""
    faults = ["LedsControl", "JointControl", "WheelsControl"]
    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Top-ranked attributed variable for each robotics attack class, across all nine "
        "robotics configurations. The documented explainability requirement for this dataset "
        "is that LED attacks attribute to a tablet sensor.",
        "tab:attributions")
    lines += ["\\begin{tabular}{lllll}", "\\toprule",
              "Algorithm & Variant & LedsControl & JointControl & WheelsControl" + NL,
              "\\midrule"]
    for ai, (algo, alabel) in enumerate(ALGOS):
        rows = read(folder(algo, "robotic") + "/outputs/explainability_top_features.csv")
        by = {}
        for r in rows:
            f_ = (r.get("Fault Name") or "").replace(".csv", "")
            v_ = (r.get("Model Variant") or "").strip()
            by.setdefault(v_, {})[f_] = (r.get("Top Variable 1") or "").strip()
        # The supervisor asked that the best configuration of each algorithm be marked,
        # since that is the row whose attribution carries the most weight. Best is by
        # AUC-ROC on this domain, read from the same metrics file Table 6.1 is built from.
        auc = {}
        for r in read(folder(algo, "robotic") + "/outputs/metrics_summary.csv"):
            try:
                auc[(r.get("Model Variant") or "").strip()] = float(r["AUC_ROC"])
            except (KeyError, TypeError, ValueError):
                pass
        top = max(auc, key=auc.get) if auc else None
        for vi, v in enumerate(VARIANTS):
            if v not in by:
                continue
            acell = (MULTIROW + alabel + "}") if vi == 0 else ""
            cells = [esc(by[v].get(f, "--")) for f in faults]
            vcell = VSHORT[v]
            if v == top:
                vcell = BF + vcell + "}"
                cells = [BF + c + "}" for c in cells]
            lines.append(acell + " & " + vcell + " & " + " & ".join(cells) + NL)
        if ai < len(ALGOS) - 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_attributions.tex", lines)


def t_shap():
    """Post-hoc SHAP attribution against intrinsic causal attribution, same grid.

    This is the comparison the reviewer asked for. It is only meaningful because SHAP now
    covers all three architectures across all three faults, matching the causal side's three
    algorithms across the same three faults.
    """
    rows = read("Baselines/outputs/shap_attribution.csv")
    if not rows:
        print("  (skipped SHAP: shap_attribution.csv absent -- rerun neural_baselines.py)")
        return
    faults = ["WheelsControl.csv", "JointControl.csv", "LedsControl.csv"]
    by = {}
    for r in rows:
        by.setdefault(r["Model Variant"], {})[r["Fault Name"]] = r["Top Variable 1"]

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Post-hoc SHAP attribution over the neural autoencoders, on the same three robotics "
        "attack classes as the causal attributions in Table~\\ref{tab:attributions}. SHAP "
        "recovers a tablet sensor for the LED attack in two of three architectures; the "
        "intrinsic causal attribution recovers one in nine of nine.",
        "tab:shap")
    lines += ["\\begin{tabular}{llll}", "\\toprule",
              "Architecture & LedsControl & JointControl & WheelsControl" + NL, "\\midrule"]
    for arch in sorted(by):
        cells = []
        for f in ["LedsControl.csv", "JointControl.csv", "WheelsControl.csv"]:
            v = by[arch].get(f, "--")
            # mark the LED->tablet hit, which is the requirement under test
            if f == "LedsControl.csv" and "Tablet" in v:
                cells.append(BF + esc(v) + "}")
            else:
                cells.append(esc(v))
        lines.append(esc(arch.replace(" Autoencoder", "")) + " & " + " & ".join(cells) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_shap.tex", lines)
    _ = faults


def t_deviation():
    """Raw standardised deviation ranks, which settle what each attribution method is doing.

    The point of the table is the gap between where a variable sits by sheer magnitude and
    whether either pipeline finds it. TabletTouchX is the answer the laboratory requirement
    asks for on the LED attack and it ranks 78th of 249 by raw deviation, far below the LED
    channels themselves; the causal attribution recovers it in 9 of 9 configurations anyway.
    Without this table that claim is unfalsifiable prose.

    No model is involved in the statistic -- it is |mean_attack - mu| / sigma against
    fault-free statistics -- so it cannot be accused of inheriting an assumption from the
    pipeline it is being used to judge.
    """
    rows = read("tools/deviation_ranks.csv")
    if not rows:
        print("  (skipped deviation: tools/deviation_ranks.csv absent)")
        return
    cap = ("Standardised deviation of each variable during the three Pepper attacks, "
           "measured against fault-free statistics with no model involved. Rank is out of the "
           "249 non-constant sensors. The variable each documented requirement names is shown "
           "with its own rank, which on the LED attack is 78th: a method that followed magnitude "
           "could not recover it.")
    lines = [
        "\\begin{table}[htbp]", "\\centering", "\\small",
    ] + caption(cap, "tab:deviation") + [
        "\\begin{tabular}{llrrl}", "\\toprule",
        "Fault & Variable & Rank & Mean $|z|$ & Requirement" + NL, "\\midrule",
    ]
    last = None
    for r in rows:
        f = r["Fault"]
        if last is not None and f != last:
            lines.append("\\midrule")
        req = r.get("Satisfies requirement", "")
        # yes: this variable is the one the requirement names. no: it is not.
        # empty: WheelsControl, for which the laboratory states no requirement.
        mark = {"yes": BF + "satisfies}", "no": "---"}.get(req, "no requirement")
        var = esc(r["Variable"])
        if req == "yes":
            var = BF + var + "}"
        lines.append(" & ".join([esc(f) if f != last else "",
                                 "\\texttt{" + var + "}",
                                 r["Rank"], r["Mean abs z"], mark]) + NL)
        last = f
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_deviation.tex", lines)


def t_density():
    """How much structure each discovered graph actually imposes, against how well it detects.

    The table pairs density with the best AUC-ROC in the same folder because the argument in
    the discussion depends on the two moving together, and a reader should be able to check
    that rather than take it. Lags are shown because they are the obvious objection: a pair
    counts as linked whenever any lag carries an edge, and PCMCI is allocated more lags than
    the others. The column is allocation, not occupancy -- GES and CAM-UV are assigned a
    single lag and populate one of their two slots, where PCMCI populates every slot it is
    given. tools/lag_depth_density.py measures the difference that makes.
    """
    rows = read("tools/graph_density.csv")
    if not rows:
        print("  (skipped density: tools/graph_density.csv absent)")
        return
    best = {}
    for algo, _ in ALGOS:
        for dom, _d in DOMAINS:
            f = folder(algo, dom).replace("\\", "/").split("/")[1]
            vals = [float(r["AUC_ROC"])
                    for r in read(folder(algo, dom) + "/outputs/metrics_summary.csv")]
            if vals:
                best[f] = max(vals)
    order = {"robotic": 0, "robotics": 0, "healthcare": 1, "industrial": 2}

    def key(r):
        f = r["Folder"].lower()
        d = next((v for k, v in order.items() if k in f), 9)
        return (d, float(r["Density"]))

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Graph density against detection performance, for all nine algorithm--domain pairs. "
        "Density is the share of variable pairs linked by at least one surviving edge, under "
        "the rule the pipeline applies. For CAM-UV that count includes the pairs assigned to "
        "a latent common cause, which the pipeline writes into the graph as dependencies; "
        "Appendix~\\ref{app:confounders} separates the two. AUC-ROC is the best of the three "
        "regression variants "
        "in that folder. On healthcare the two move together monotonically; on industrial the "
        "ordering reverses; on robotics the comparison is confounded by PCMCI operating on "
        "244 variables against 35, which is why the best score is marked in the other two "
        "domains and not in that one.",
        "tab:density")
    lines += ["\\begin{tabular}{llrrrr}", "\\toprule",
              "Domain & Algorithm & Vars & Lags & Density & Best AUC-ROC $\\uparrow$" + NL,
              "\\midrule"]
    body = []
    for r in sorted(rows, key=key):
        f = r["Folder"]
        fl = f.lower()
        dom = ("Robotics" if ("robotic" in fl) else
               "Healthcare" if "healthcare" in fl else "Industrial")
        auc = best.get(f)
        algo = ("PCMCI" if "pcmci" in fl else
                "CAM-UV" if ("cam_uv" in fl or "camuv" in fl) else "GES")
        body.append([dom, algo, r["Variables"], r["Lags"],
                     "%.1f\\%%" % (100 * float(r["Density"])),
                     ("%.4f" % auc) if auc else "--"])
    # A domain block is bolded only when its three rows were discovered over the same
    # number of variables. Healthcare and industrial were; robotics was not, because
    # PCMCI runs there over 244 variables against 35, and the caption already says that
    # comparison is confounded. Bolding a cell in that block would assert on the page a
    # ranking the caption withdraws two lines below it.
    i = 0
    while i < len(body):
        j = i
        while j < len(body) and body[j][0] == body[i][0]:
            j += 1
        if len({row[2] for row in body[i:j]}) == 1:
            bold_best(body[i:j], [5])
        i = j
    last = None
    for cells in body:
        if last is not None and cells[0] != last:
            lines.append("\\midrule")
        dom = cells[0]
        lines.append(" & ".join([dom if dom != last else ""] + cells[1:]) + NL)
        last = dom
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_density.tex", lines)


# Tables 6.2 to 6.4 name the three regression variants in short form. This table
# used the long form for the same three, which was both wider and inconsistent.
SHORT_VARIANT = {"Linear / Ridge": "Linear",
                 "Polynomial degree 3": "Poly-3",
                 "RBF + Ridge": "RBF"}


def t_baseline_parity():
    """What the causal side and the baseline side were actually given, per domain.

    Section 6.4 declares an asymmetry that runs against the thesis: on healthcare the
    autoencoders see 7143 fault-free samples where the causal configuration they are
    compared against sees 5000. The declaration is the honest thing to do, but in prose it
    asks the reader to take it on trust. The table lets them check it, and shows that the
    other two domains are matched exactly.

    The variable columns are collapsed into one because the CSV records them equal in every
    domain, which is itself part of the claim: the difference is one of resolution alone.
    """
    rows = read("tools/baseline_parity.csv")
    if not rows:
        print("  (skipped baseline parity: tools/baseline_parity.csv absent)")
        return
    for r in rows:
        if r["Baseline variables"] != r["Causal variables"]:
            raise SystemExit(
                "baseline_parity: %s has %s baseline variables against %s causal. The "
                "table collapses them into one column on the assumption they are equal, "
                "and Section 6.4 states that the difference is one of resolution alone. "
                "Both are now wrong -- fix the text, not this check."
                % (r["Domain"], r["Baseline variables"], r["Causal variables"]))

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "What each side of the baseline comparison was given. The variable set is identical "
        "within every domain, so a single column carries it; the difference, where there is "
        "one, is the subsampling rate and therefore the number of fault-free samples. "
        "Robotics and industrial are matched exactly. Healthcare is not, and the direction "
        "runs against the thesis: the autoencoders are fitted on 7{,}143 fault-free samples "
        "where the best causal configuration sees 5{,}000, so the causal margin reported for "
        "that domain is measured against a better-resourced opponent instead of a "
        "handicapped one.",
        "tab:baseline_parity")
    # tabularx, not tabular. The natural width of this table ran 51.58pt past the
    # text block -- about 1.8cm into the margin, and plainly visible. X absorbs the
    # excess in the one column that can wrap, so the fit is guaranteed rather than
    # estimated. The @{} pair recovers the outer inter-column padding as well.
    lines += ["\\begin{tabularx}{\\textwidth}{@{}l X r r r r r c@{}}", "\\toprule",
              "\\multirow{2}{*}{Domain} & \\multirow{2}{*}{Best causal} & "
              "\\multirow{2}{*}{Vars} & \\multicolumn{2}{c}{Subsample} & "
              "\\multicolumn{2}{c}{Fault-free samples} & \\multirow{2}{*}{Matched}" + NL,
              "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
              " & & & Neural & Causal & Neural & Causal & " + NL, "\\midrule"]
    for r in rows:
        lines.append(" & ".join([
            esc(r["Domain"]),
            esc("%s, %s" % (r["Best causal algorithm"],
                            SHORT_VARIANT.get(r["Best causal variant"].strip(),
                                              r["Best causal variant"]))),
            r["Causal variables"],
            r["Baseline subsample"], r["Causal subsample"],
            r["Baseline fault-free samples"], r["Causal fault-free samples"],
            "yes" if r["Resolution matched"].strip().lower() == "yes" else "no"]) + NL)
    lines += ["\\bottomrule", "\\end{tabularx}", "\\end{table}"]
    write("tbl_baseline_parity.tex", lines)


def t_runtime():
    """Wall-clock detection cost of all 27 configurations.

    measure_runtime.py has been writing this CSV, and Appendix~\\ref{app:code} advertises the
    tool, but no chapter reported the result. Cost is the first question asked of a method
    proposed for an industrial or clinical deployment, and the answer existed unpublished.

    The variable and subsample columns are not decoration. They are the reason the table
    cannot be read as a ranking: PCMCI runs robotics at 244 variables where the others run
    35, and industrial at every sample where the others take one in ten. No domain puts the
    three algorithms on the same workload, so these figures bound the cost of each
    configuration as it was actually run and support no cross-algorithm claim.
    """
    rows = read("tools/runtime.csv")
    if not rows:
        print("  (skipped runtime: tools/runtime.csv absent)")
        return
    names = {"TS-CAM-UV": "CAM-UV"}
    aorder = {"PCMCI": 0, "GES": 1, "CAM-UV": 2}
    dorder = {"robotics": 0, "robotic": 0, "healthcare": 1, "industrial": 2}
    dname = {"robotics": "Robotics", "robotic": "Robotics",
             "healthcare": "Healthcare", "industrial": "Industrial"}

    def key(r):
        a = names.get(r["Algorithm"], r["Algorithm"])
        return (aorder.get(a, 9), dorder.get(r["Domain"].lower(), 9), r["Variant"])

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Wall-clock detection time for all 27 configurations, in seconds. All 27 were "
        "measured in one session on the machine that produced every result in this "
        "dissertation: an Intel Core i5-8250U at 1.60~GHz, four cores and eight "
        "threads, with 32~GB of memory, under Windows 11. That is a 15~W mobile "
        "processor and not a workstation, which is worth knowing in both "
        "directions: it makes the modest absolute cost reported here a stronger claim, "
        "and it is the machine on which the 160-variable GES run failed to converge. "
        "The timing harness refuses to start under CPU contention, so no other work "
        "distorted these figures; "
        "they remain specific to that machine and only the relative magnitudes travel. Discovery is "
        "cached and excluded; these are the detection runs. The variable and subsample "
        "columns are given because "
        "they prevent the table from being read as a ranking: on robotics PCMCI works over "
        "244 variables where the other two work over 35, and on industrial it uses every "
        "sample where they take one in ten. No domain presents the three algorithms with the "
        "same workload, so the figures bound the cost of each configuration as it was run "
        "and support no comparison between algorithms.",
        "tab:runtime")
    lines += ["\\begin{tabular}{lllrrr}", "\\toprule",
              "Algorithm & Domain & Variant & Vars & Subs. & Seconds $\\downarrow$" + NL, "\\midrule"]
    last = None
    for r in sorted(rows, key=key):
        a = names.get(r["Algorithm"], r["Algorithm"])
        if last is not None and a != last:
            lines.append("\\midrule")
        d = r["Domain"].lower()
        lines.append(" & ".join([
            esc(a) if a != last else "",
            dname.get(d, esc(r["Domain"])),
            esc(r["Variant"]),
            r["Variables"], r["Subsample"],
            "%.1f" % float(r["Detection seconds"])]) + NL)
        last = a
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_runtime.tex", lines)


def t_lead_ablation():
    """Density and detection across the eight-lead restriction, over a common denominator.

    Section~\\ref{sec:eight-lead-ablation} makes a three-way comparison -- two densities and
    two AUCs for each of three algorithms -- and made it entirely in prose, which asks the
    reader to hold twelve numbers in mind to see the sign flip. The table exists so the flip
    can be seen instead of reconstructed: GES and CAM-UV gain density and lose AUC, PCMCI
    holds density exactly and gains.

    Both density columns are counted over the same 28 pairs. That is the point of the
    restriction, and without it the comparison would be against a 66-pair denominator and
    the fraction would rise on its own.
    """
    rows = read("tools/lead_ablation_density.csv")
    if not rows:
        print("  (skipped lead ablation: tools/lead_ablation_density.csv absent)")
        return
    # The CSV was written before the naming was settled; the dissertation says CAM-UV.
    names = {"TS-CAM-UV": "CAM-UV"}
    order = {"PCMCI": 0, "GES": 1, "CAM-UV": 2}

    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "The eight-lead ablation over a common denominator. Removing the four leads that are "
        "exact linear combinations of the others leaves 28 variable pairs; both density "
        "columns are counted over those same 28, so the twelve-lead figure is its graph "
        "restricted to the eight retained leads, not its own 66-pair density. Mean "
        "AUC-ROC is averaged over the three regression variants. GES and CAM-UV gain density "
        "and lose accuracy, as Section~\\ref{sec:density} predicts; PCMCI links an identical "
        "26 pairs under both conditions and gains, so its improvement cannot be a density "
        "effect and is attributed to relieved multicollinearity.",
        "tab:lead_ablation")
    lines += ["\\begin{tabular}{lcrrrrr}", "\\toprule",
              "Algorithm & Linked 12/8 & Dens.\\ 12 & Dens.\\ 8 & "
              "AUC 12 $\\uparrow$ & AUC 8 $\\uparrow$ & $\\Delta$ AUC $\\uparrow$" + NL, "\\midrule"]
    def key(r):
        return order.get(names.get(r["Algorithm"], r["Algorithm"]), 9)
    body = []
    for r in sorted(rows, key=key):
        d = float(r["Mean AUC delta"])
        body.append([
            esc(names.get(r["Algorithm"], r["Algorithm"])),
            "%s / %s" % (r["Linked 12-lead graph over 8 leads"], r["Linked 8-lead graph"]),
            "%.1f\\%%" % (100 * float(r["Density 12-lead subset"])),
            "%.1f\\%%" % (100 * float(r["Density 8-lead"])),
            "%.4f" % float(r["Mean AUC 12-lead"]),
            "%.4f" % float(r["Mean AUC 8-lead"]),
            "%s%.4f" % ("+" if d > 0 else "", d)])
    # All three algorithms are measured here on one domain over a common 28 pairs, which
    # is the whole point of the restriction, so the columns are directly comparable and
    # the best cell in each is a real best. The density columns are descriptive rather
    # than good or bad in either direction and are left unmarked.
    bold_best(body, [4, 5, 6])
    for cells in body:
        lines.append(" & ".join(cells) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_lead_ablation.tex", lines)


def t_parent_cap():
    """How much of each graph survives the three-parent regression cap.

    This table exists because the density argument needs it. `fit_normal_coeffs` keeps only
    the three shortest-lag parents of each target, so no regression is ever wider than three
    columns plus an intercept, however dense the graph. Density therefore cannot act on
    detection by enlarging the regression, and the discussion had claimed it did.

    The column that carries the argument is the last one. The cap does not fall evenly: it
    removes almost everything PCMCI found on robotics and nothing at all of what GES found,
    so those two graphs are not represented on equal terms in the comparison that follows.
    """
    rows = read("tools/parent_cap_bite.csv")
    if not rows:
        print("  (skipped parent cap: tools/parent_cap_bite.csv absent)")
        return
    order = {"Robotics": 0, "Healthcare": 1, "Industrial": 2}
    lines = ["\\begin{table}[htbp]", "\\centering", "\\small"]
    lines += caption(
        "Bite of the three-parent regression cap, for all nine algorithm--domain pairs. "
        "A target is regressed on at most three parents, chosen by shortest lag, so the "
        "design matrix is never wider than three columns plus an intercept. Targets are "
        "those variables the graph gives at least one parent. The final column is the share "
        "of discovered edges the cap discards, and it is what prevents graph density from "
        "acting through regression size: on robotics it removes 98.2\\% of what PCMCI "
        "found and none of what GES found.",
        "tab:parentcap")
    lines += ["\\begin{tabular}{llrrrr}", "\\toprule",
              "Domain & Algorithm & Targets & Edges & Capped & Edges dropped" + NL,
              "\\midrule"]
    last = None
    for r in sorted(rows, key=lambda r: (order.get(r["Domain"], 9),
                                         -float(r["Percent of edges discarded"]))):
        dom = r["Domain"]
        if last is not None and dom != last:
            lines.append("\\midrule")
        lines.append(" & ".join([
            dom if dom != last else "",
            esc(r["Algorithm"]),
            r["Modelled targets"],
            r["Edges after sparsification"],
            "%s\\%%" % r["Percent of targets capped"],
            "%s\\%%" % r["Percent of edges discarded"]]) + NL)
        last = dom
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_parent_cap.tex", lines)


def t_attributions_full():
    """The complete top-3 attribution for every configuration and every attack class.

    Chapter 6 shows only the robotics top-1, because that is what the laboratory
    requirement is stated over and because 387 rows is not a readable table. This is the
    appendix version: every fault in every configuration, so a reader can confirm that the
    robotics result was not selected out of a larger set that mostly disagreed.

    Healthcare and industrial carry 20 attack classes each, so those tables are long. They
    are emitted as longtable, which breaks across pages; the robotics table has three
    classes and fits.
    """
    for dom, label in (("robotic", "Robotics"), ("healthcare", "Healthcare"),
                       ("industrial", "Industrial")):
        rows = []
        for algo, alabel in ALGOS:
            for r in read(folder(algo, dom) + "/outputs/explainability_top_features.csv"):
                rows.append((alabel, r.get("Model Variant", ""),
                             (r.get("Fault Name") or "").replace(".csv", ""),
                             r.get("Top Variable 1", ""), r.get("Top Variable 2", ""),
                             r.get("Top Variable 3", "")))
        if not rows:
            continue
        # Robotics sensor names run long -- LShoulderPitchTemp, LaserShovel03X -- and at
        # \small this table overflowed the text block by 76.8pt. The font step plus
        # tighter column padding brings all three domains inside it.
        long = len(rows) > 40
        lines = []
        if not long:
            lines += ["\\begin{table}[htbp]", "\\centering", "\\scriptsize",
                      "\\setlength{\\tabcolsep}{4pt}"]
        else:
            # A longtable is not a float, so nothing scopes the size declaration for it.
            # Left bare, \scriptsize leaks past \end{longtable} into whatever follows the
            # \input -- the next subsection's body text was being set in it. The braces
            # confine both declarations to the table.
            lines += ["{\\scriptsize", "\\setlength{\\tabcolsep}{4pt}"]
        cap = ("Complete top-three attribution for the " + label.lower() + " domain, every "
               "configuration and every attack class. The ranking rule is stated in "
               "Section~\\ref{sec:method-attribution}.")
        if long:
            lines += ["\\begin{longtable}{llllll}",
                      cap_open(cap) + cap + "}\\label{app:attr-" + dom + "}\\\\",
                      "\\toprule",
                      "Algorithm & Variant & Fault & First & Second & Third" + NL,
                      "\\midrule", "\\endfirsthead",
                      "\\toprule",
                      "Algorithm & Variant & Fault & First & Second & Third" + NL,
                      "\\midrule", "\\endhead"]
        else:
            lines += caption(cap, "app:attr-" + dom)
            lines += ["\\begin{tabular}{llllll}", "\\toprule",
                      "Algorithm & Variant & Fault & First & Second & Third" + NL,
                      "\\midrule"]
        # Row order came from each CSV's file order. The detection scripts rewrite their
        # own rows on a re-run, so re-running one configuration reshuffled this table --
        # and because the algorithm cell is blanked on repeats, the label jumped to
        # whichever row happened to land first. Sorting makes the table a function of the
        # data rather than of the order the pipeline was last run in.
        _ao = {a[1]: i for i, a in enumerate(ALGOS)}
        _vo = {"Linear / Ridge": 0, "Polynomial degree 3": 1, "RBF + Ridge": 2}
        # Robotics attack names carry no number, so a digit key would sort them
        # alphabetically and reorder the published table. Pinned to the order the
        # laboratory uses and Table B.1 already prints.
        _fo = {"WheelsControl": 0, "JointControl": 1, "LedsControl": 2}
        def _fkey(x):
            b = x[:-4] if x.endswith(".csv") else x
            if b in _fo:
                return (0, _fo[b], "")
            d = "".join(c for c in x if c.isdigit())
            return (0, int(d), "") if d else (1, 0, b)
        rows.sort(key=lambda r: (_ao.get(r[0], 9), _vo.get(r[1], 9), _fkey(r[2])))
        last = None
        for a, v, f, t1, t2, t3 in rows:
            acell = a if a != last else ""
            last = a
            lines.append(" & ".join([acell, VSHORT.get(v, v), esc(fault_label(f)),
                                     "\\texttt{" + esc(t1) + "}",
                                     "\\texttt{" + esc(t2) + "}",
                                     "\\texttt{" + esc(t3) + "}"]) + NL)
        lines += ["\\bottomrule"]
        lines += ["\\end{longtable}}"] if long else ["\\end{tabular}", "\\end{table}"]
        write("tbl_attr_full_" + dom + ".tex", lines)



# ------------------------------------------------- PC versus PCMCI under autocorrelation
def t_pc_pcmci():
    """The measurement Chapter 2 promises and Chapter 6 was not reporting.

    Three columns matter and only two were ever quoted. PC's false-positive rate climbs
    twelve-fold as autocorrelation rises. PCMCI's is flat in phi -- which is the claim the
    algorithm selection rests on -- but its LEVEL depends on whether the false-discovery
    correction is applied, and the pipeline calls run_pcmci without it. Reporting only the
    corrected column would quote a configuration this thesis does not run.
    """
    rows = read("tools/pc_vs_pcmci.csv")
    if not rows:
        print("  (skipped pc_vs_pcmci: CSV absent)")
        return
    meta = rows[0]
    lines = ["\\begin{table}[htbp]", "\\centering"]
    lines += caption(
        "False-positive rate of PC against PCMCI on synthetic data built to contain no "
        "cross-variable edges, so every reported link is a false positive by construction. "
        "The sweep varies the autocorrelation coefficient $\\phi$ over "
        + esc(meta.get("variables", "")) + " variables and "
        + esc(meta.get("samples", "")) + " samples, averaged over "
        + esc(meta.get("seeds", "")) + " seeds at $\\alpha = "
        + esc(meta.get("alpha", "")) + "$. PC degrades sharply; PCMCI does not degrade at "
        "all, which is why it is the constraint-based representative here. The last two "
        "columns are the same algorithm with and without the false-discovery correction: "
        "the pipeline runs the uncorrected variant, so that column describes the "
        "configuration evaluated in this thesis and the corrected one does not.",
        "tab:pcpcmci")
    lines += ["\\begin{tabular}{lrrr}", "\\toprule",
              "$\\phi$ & PC $\\downarrow$ & PCMCI, as run $\\downarrow$ & "
              "PCMCI, FDR $\\downarrow$" + NL, "\\midrule"]
    for r in rows:
        lines.append(" & ".join([
            esc(r.get("phi", "")),
            esc(r.get("PC false positive rate", "")),
            esc(r.get("PCMCI uncorrected", "")),
            esc(r.get("PCMCI FDR", "")),
        ]) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_pc_pcmci.tex", lines)


# ------------------------------------------------------------------------ DeLong
def _cfg(label):
    """CAM_UV_healthcare Linear / Ridge  ->  CAM-UV Linear."""
    parts = label.split(" ", 1)
    folder = parts[0]
    variant = parts[1] if len(parts) > 1 else ""
    algo = ("CAM-UV" if folder.startswith("CAM") else
            "GES" if folder.startswith("GES") else "PCMCI")
    return algo + " " + VSHORT.get(variant, variant)


def t_delong():
    """Contribution C6 had no table anywhere in the document.

    The claim that 54 of 108 within-domain comparisons admit no paired test appears in the
    abstract and in four chapters, and until now a reader had no way to see which 54 or
    why. Two tables: a per-domain summary for the results chapter, and the full paired
    result set for the appendix.
    """
    tests = read("tools/delong_tests.csv")
    unpair = read("tools/delong_not_pairable.csv")
    if not tests:
        print("  (skipped delong: CSV absent)")
        return

    # ---- summary, for Chapter 6
    doms = []
    for r in tests:
        d = r.get("Dataset", "")
        if d not in doms:
            doms.append(d)
    lines = ["\\begin{table}[htbp]", "\\centering"]
    lines += caption(
        "Paired AUC comparisons by DeLong's test, by domain. Every within-domain pair of "
        "the nine configurations is counted, so each domain contributes 36. A pair is "
        "testable only when both configurations score the same observations, which fails "
        "wherever PCMCI is on exactly one side of the comparison because it "
        "subsamples at its own rate; two PCMCI configurations share a sample set "
        "with each other and are testable, which is what makes the split 18 and 18 "
        "rather than 21 and 15. The unpairable column is the cost of treating the subsampling rate as a "
        "property of each algorithm and not as a pipeline constant.",
        "tab:delong-summary")
    lines += ["\\begin{tabular}{lrrrr}", "\\toprule",
              "Domain & Comparisons & Testable $\\uparrow$ & Unpairable $\\downarrow$ & Significant $\\uparrow$" + NL, "\\midrule"]
    tot = [0, 0, 0, 0]
    for d in doms:
        t = [r for r in tests if r.get("Dataset") == d]
        u = [r for r in unpair if r and list(r.values())[0] == d]
        sig = len([r for r in t if r.get("Significant", "").strip() == "yes"])
        row = [len(t) + len(u), len(t), len(u), sig]
        for i, v in enumerate(row):
            tot[i] += v
        lines.append(" & ".join([esc(d)] + [str(v) for v in row]) + NL)
    lines += ["\\midrule",
              " & ".join(["\\textbf{All three}"] + ["\\textbf{" + str(v) + "}" for v in tot]) + NL,
              "\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_delong_summary.tex", lines)

    # ---- the full 54, for Appendix B
    #
    # 54 comparisons plus three domain headings and their rules is over sixty rows, which no
    # float can hold: as a table it would have raised "Float too large for page" and then
    # drifted to the end of the appendix looking for somewhere to land. longtable breaks it
    # across pages and repeats the header, and the package is already loaded for the
    # attribution tables. The braces confine \footnotesize, which nothing else scopes once
    # the table is no longer a float.
    cap = ("Every testable paired comparison, by DeLong's test. $\\Delta$ is AUC$_A$ minus "
           "AUC$_B$; $p$ is two-sided and is set in bold where it clears $\\alpha = 0.05$. Pairs absent from this table are the 54 that share no "
           "sample set; the tool that writes this table also writes those, with the "
           "reason each one fails, to a companion CSV.")
    head = "A & B & AUC$_A$ & AUC$_B$ & $\\Delta$ & $z$ & $p$" + NL
    lines = ["{\\footnotesize",
             "\\begin{longtable}{llrrrrr}",
             cap_open(cap) + cap + "}\\label{tab:delong-full}\\\\",
             "\\toprule", head, "\\midrule", "\\endfirsthead",
             "\\toprule", head, "\\midrule", "\\endhead"]
    seen = None
    for r in tests:
        d = r.get("Dataset", "")
        if d != seen:
            if seen is not None:
                lines.append("\\midrule")
            lines.append("\\multicolumn{7}{l}{\\textit{" + esc(d) + "}}" + NL)
            seen = d
        # No column here has a good direction -- a difference is not better for being
        # large and a p-value is not better for being small -- so an arrow would say
        # nothing. What a reader wants marked is which rows cleared the threshold, and
        # the CSV already carries that verdict rather than it being recomputed here.
        sig = r.get("Significant", "").strip() == "yes"
        pcell = esc(r.get("p", ""))
        lines.append(" & ".join([
            esc(_cfg(r.get("A", ""))), esc(_cfg(r.get("B", ""))),
            esc(r.get("AUC_A", "")), esc(r.get("AUC_B", "")),
            esc(r.get("Difference", "")), esc(r.get("z", "")),
            (BF + pcell + "}") if sig else pcell,
        ]) + NL)
    lines += ["\\bottomrule", "\\end{longtable}}"]
    write("tbl_delong_full.tex", lines)

# --------------------------------------------------------- explainability metrics
DOMS = [("robotics", "Robotics (Pepper)"),
        ("healthcare", "Healthcare (PTB-XL)"),
        ("industrial", "Industrial (TEP)")]


def attribution_ci():
    """The intervals written by tools/attribution_intervals.py, keyed for lookup.

    Returns two dicts: marginal intervals by (kind, domain, rule, method), and
    paired differences by (kind, domain, rule, against).
    """
    marg, paired = {}, {}
    for r in read("tools/attribution_intervals.csv"):
        k = r["kind"]
        if k.endswith("_paired"):
            paired[(k, r["domain"], r["rule"], r["against"])] = r
        else:
            marg[(k, r["domain"], r["rule"], r["method"])] = r
    return marg, paired


def t_relevance():
    """How often the top-attributed variables are the ones the fault actually touched.

    The headline explainability number, and the reason the chance column is carried
    beside it: 71 of the 244 robot sensors have led or tablet in the name, so a method
    picking at random already scores 29\\% there, while on the Tennessee Eastman
    plant, where one actuator out of 52 is the documented cause, chance is 2\\%.
    Comparing the raw percentages across domains without that column would rank the
    domains backwards.
    """
    by = {}
    for r in read("tools/relevance_by_class.csv"):
        by.setdefault((r["domain"], r["algorithm"], r["rule"]), []).append(
            (float(r["relevance_pct"]), float(r["chance_pct"])))
    methods = ["PCMCI", "GES", "CAM-UV", "SHAP"]
    # Ten columns, two of them intervals, is the widest table in the dissertation.
    # At \small with default padding and the domain names spelled out it ran past the
    # right margin and the last Lift column fell off the page entirely. The font step,
    # the tighter padding, the bare en-dash interval and the short domain labels bring
    # it back inside the text block; the corpus names are in Table~\ref{tab:datasets}.
    SHORT_DOM = {"Robotics (Pepper)": "Robotics",
                 "Healthcare (PTB-XL)": "Healthcare",
                 "Industrial (TEP)": "Industrial"}
    lines = ["\\begin{table}[htbp]", "\\centering", "\\footnotesize",
             "\\setlength{\\tabcolsep}{3pt}"]
    lines += caption(
        "Relevance of the top-attributed variables against the documented cause of each "
        "anomaly class, for the three causal algorithms and for post-hoc SHAP on the "
        "neural baselines. Chance is the share of variables that are relevant for that "
        "class, so lift is the factor by which a method beats random selection. SHAP is "
        "computed on all three datasets, over the same anomaly classes the causal "
        "pipeline is scored on. Classes with no documented cause are excluded rather "
        "than guessed at, and the Cls.\\ column is how many survive that exclusion: the robotics dataset defines three attacks, "
        "the industrial specification documents an actuator for five of its twenty "
        "faults, and fourteen of the twenty cardiac classes localise to lead territory. "
        "Those are the sample sizes this section rests on. The interval is a cluster "
        "bootstrap resampling whole classes, and it is wide because the class counts are "
        "small. Bold marks the highest point estimate in each domain and nothing more; "
        "Table~\\ref{tab:attr-paired} reports which of these differences a paired test "
        "separates at the depth this thesis states its attribution results at, and "
        "Table~\\ref{tab:attr-paired-full} does the same at every depth. Most are "
        "not separated, and on the robot and the plant most are not tested at all: "
        "three and five classes cannot reach the 5\\% level however the numbers "
        "fall, which is a different statement and the weaker one.",
        "tab:relevance")
    marg, _paired = attribution_ci()
    # Chance is the share of the variable pool that counts as relevant for the class.
    # It does not depend on how many variables the method is allowed to name, so the
    # old layout printed the identical figure under Top-3 and again under Top-5. Lifting
    # it to a single column costs nothing and pays for both intervals.
    lines += ["\\begin{tabular}{llrrrrrrrr}", "\\toprule",
              "& & & & \\multicolumn{3}{c}{Top-3} & \\multicolumn{3}{c}{Top-5}" + NL,
              "\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}",
              "Dataset & Method & Cls. & Chance\\% & Rel.\\% $\\uparrow$ & 95\\% CI & "
              "Lift $\\uparrow$ & Rel.\\% $\\uparrow$ & 95\\% CI & Lift $\\uparrow$" + NL,
              "\\midrule"]
    for di, (dom, dlabel) in enumerate(DOMS):
        present = [m for m in methods if (dom, m, "top3") in by]
        block = []
        ncls = ""
        for m in present:
            cells, chance = [], None
            for rule in ("top3", "top5"):
                v = by[(dom, m, rule)]
                pct = sum(x[0] for x in v) / len(v)
                ch = sum(x[1] for x in v) / len(v)
                chance = ch if chance is None else chance
                ci = marg.get(("relevance", dom, rule, m))
                ncls = ci["n_classes"] if ci else ncls
                cells += ["%.1f" % pct,
                          ("%s--%s" % (ci["ci_low"], ci["ci_high"])) if ci else "--",
                          ("%.2f" % (pct / ch)) if ch else "--"]
            block.append(["%.1f" % chance] + cells)
        # Chance is a property of the pool rather than an achievement and is not ranked;
        # neither is an interval, nor the class count. The bold marks the highest point
        # estimate only -- which of these differences survives a test is
        # Table~\ref{tab:attr-paired}, and most of them do not.
        block = bold_best(block, [1, 3, 4, 6])
        short = SHORT_DOM.get(dlabel, dlabel)
        for mi, (m, cells) in enumerate(zip(present, block)):
            dcell = ("\\multirow{%d}{*}{%s}" % (len(present), short)) if mi == 0 else ""
            ccell = ("\\multirow{%d}{*}{%s}" % (len(present), ncls)) if mi == 0 else ""
            lines.append(dcell + " & " + m + " & " + ccell + " & "
                         + " & ".join(cells) + NL)
        if di < len(DOMS) - 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_relevance.tex", lines)


def _paired_rows():
    rows = read("tools/attribution_intervals.csv")
    return [r for r in rows if r["kind"] == "relevance_paired"]


DOM_ORDER = {"robotics": 0, "healthcare": 1, "industrial": 2}
DOM_NAME = {"robotics": "Robotics", "healthcare": "Healthcare",
            "industrial": "Industrial"}
RULE_ORDER = {"top3": 0, "top5": 1, "top10": 2, "std1": 3}
RULE_NAME = {"top3": "Top-3", "top5": "Top-5", "top10": "Top-10",
             "std1": "$z>1$"}


def _sign_cell(r):
    """How the classes split: favouring SHAP, favouring the causal side, tied.

    An earlier version printed only the first over the class count, so a 2--0--1
    split read as 2--1 and a unanimous panel looked divided. Ties carry no
    evidence either way and the sign test discards them, so they are shown
    rather than folded into the losing side.
    """
    return "%s/%s/%s" % (r["n_pos"], r["n_neg"], r["n_tie"])


def _verdict(r):
    return {"yes": "yes", "no": "no"}.get(r["separates"], "---")


def t_attr_paired():
    """The primary attribution comparison: the pre-specified depth, Holm-corrected.

    Section 4.6 fixes the top-three ranking as the depth at which every
    attribution result in this thesis is stated, so that is the family, three
    comparisons within each domain, and Holm's correction runs across them. The
    other three depths are exploratory and are tabulated in Appendix B rather
    than dropped, because choosing the depth after seeing the result is the
    failure this section exists to avoid.
    """
    rows = [r for r in _paired_rows() if r["rule"] == "top3"]
    if not rows:
        print("  (skipped attribution paired: CSV absent)")
        return
    n_sep = len([r for r in rows if r["separates"] == "yes"])
    n_na = len([r for r in rows if r["separates"] == "n/a"])
    words = {0: "None", 1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five",
             6: "Six", 7: "Seven", 8: "Eight", 9: "Nine"}
    lines = ["\\begin{table}[htbp]", "\\centering", "\\footnotesize",
             "\\setlength{\\tabcolsep}{4pt}"]
    lines += caption(
        "Paired differences in attribution relevance at the top-three depth, SHAP "
        "minus each causal algorithm, over the anomaly classes both were scored on. "
        "A positive value favours SHAP. The test is an exact paired sign test, not "
        "the bootstrap interval, which is reported beside it as a descriptive range "
        "only: the interval rule cannot state its own level, whereas the sign test "
        "can, and its smallest attainable two-sided value on $n$ classes that are "
        "not tied is exactly $2^{1-n}$. That is 0.25 at best on the robot's three "
        "attack classes and 0.0625 at best on the plant's five documented actuators, "
        "and ties are discarded and so raise those floors rather than lowering them. "
        "Neither panel can return a result at the 5\\% level however large the "
        "difference, and both are dashed rather than answered. The Sign column splits the "
        "classes into those favouring SHAP, those favouring the causal side and "
        "those tied; ties carry no evidence and the test discards them. This is the "
        "depth Section~\\ref{sec:method-attribution} fixes for every attribution "
        "result in this thesis, so the three comparisons within a domain form one "
        "family and $p$ is Holm-adjusted across them. The other three depths are "
        "exploratory and are tabulated in full as Table~\\ref{tab:attr-paired-full}. "
        + words.get(n_sep, str(n_sep))
        + (" of the nine rows separates and " if n_sep == 1
           else " of the nine rows separate and ")
        + words.get(n_na, str(n_na)).lower()
        + (" carries no verdict at all." if n_na == 1
           else " carry no verdict at all."),
        "tab:attr-paired")
    lines += ["\\begin{tabular}{llrrcrc}", "\\toprule",
              "Dataset & Comparison & Cls. & $\\Delta$ Rel.\\% & Sign & "
              "Holm $p$ & Separable" + NL, "\\midrule"]
    last = None
    for r in sorted(rows, key=lambda r: (DOM_ORDER.get(r["domain"], 9), r["against"])):
        dom = DOM_NAME.get(r["domain"], r["domain"])
        if last is not None and dom != last:
            lines.append("\\midrule")
        d = float(r["value"])
        val = "%s%.1f" % ("+" if d > 0 else "", d)
        sep = r["separates"] == "yes"
        # A panel that cannot reach 0.05 has no p worth printing either: showing
        # one invites the reader to compare numbers that decide nothing.
        ph = "---" if r["separates"] == "n/a" else (r["p_holm"] or "---")
        lines.append(" & ".join([
            dom if dom != last else "",
            "SHAP $-$ " + r["against"],
            r["n_classes"],
            (BF + val + "}") if sep else val,
            _sign_cell(r),
            ph,
            _verdict(r)]) + NL)
        last = dom
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_attr_paired.tex", lines)


def t_attr_paired_full():
    """Every paired attribution comparison the study computes, at all four depths.

    Tabulated in full because the alternative is to choose which depths to show
    after seeing what they say, and one of them -- GES at ten variables on the
    electrocardiogram -- reverses the ordering. That row is marked degenerate:
    GES ranks nine of the twelve leads, so at a depth of ten it returns all nine
    and its relevance is forced to equal its chance rate. It is not ranking at
    that depth and the comparison measures the pool rather than the method.
    """
    rows = _paired_rows()
    if not rows:
        return
    cap = ("Every paired attribution comparison, at all four reporting depths. "
           "$\\Delta$ is SHAP minus the causal algorithm, so positive favours SHAP. "
           "Sign splits the classes into those favouring SHAP, those favouring the "
           "causal side and those tied. $p$ is an exact two-sided paired sign test "
           "with ties discarded; it is Holm-adjusted within a domain at the top-three "
           "depth, which Section~\\ref{sec:method-attribution} pre-specifies, and "
           "reported uncorrected at the other three, which are exploratory. A dash "
           "means the panel cannot reach the 5\\% level at all, its smallest "
           "attainable $p$ being $2^{1-n}$. A dagger marks a degenerate comparison, "
           "one in which a method's selection depth reaches the pool it ranks so that "
           "it returns everything it has: GES ranks nine of the twelve "
           "electrocardiogram leads, so at ten variables it scores exactly chance by "
           "construction and the row measures the pool and not the method.")
    head = ("Dataset & Depth & Comparison & Cls. & $\\Delta$ Rel.\\% & Sign & $p$ & "
            "Sep." + NL)
    lines = ["{\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
             "\\begin{longtable}{lllrrcrc}",
             cap_open(cap) + cap + "}\\label{tab:attr-paired-full}\\\\",
             "\\toprule", head, "\\midrule", "\\endfirsthead",
             "\\toprule", head, "\\midrule", "\\endhead"]
    last = None
    for r in sorted(rows, key=lambda r: (DOM_ORDER.get(r["domain"], 9),
                                         RULE_ORDER.get(r["rule"], 9),
                                         r["against"])):
        dom = DOM_NAME.get(r["domain"], r["domain"])
        if last is not None and dom != last:
            lines.append("\\midrule")
        d = float(r["value"])
        val = "%s%.1f" % ("+" if d > 0 else "", d)
        sep = r["separates"] == "yes"
        p = r["p_holm"] if r["p_holm"] else r["p_exact"]
        if r["separates"] == "n/a":
            p = "---"
        lines.append(" & ".join([
            dom if dom != last else "",
            RULE_NAME.get(r["rule"], r["rule"]),
            "SHAP $-$ " + r["against"] + ("$^\\dagger$" if r["degenerate"] == "yes" else ""),
            r["n_classes"],
            (BF + val + "}") if sep else val,
            _sign_cell(r),
            p,
            _verdict(r)]) + NL)
        last = dom
    lines += ["\\bottomrule", "\\end{longtable}}"]
    write("tbl_attr_paired_full.tex", lines)


def t_consistency():
    """Whether the methods agree with each other on which variables explain a class.

    Relevance asks whether a method points at the right variables; this asks whether
    independent methods point at the same ones. The chance column matters more here
    than anywhere else, because the Jaccard index rises on its own as the selected set
    grows relative to the number of variables: two random sets of ten drawn from twelve
    ECG leads overlap almost completely, and without the baseline the ECG would look
    like the most consistent domain by arithmetic alone.
    """
    by = {}
    for r in read("tools/consistency_by_class.csv"):
        by.setdefault((r["domain"], r["family"], r["top_k"]), []).append(
            (float(r["mean_jaccard"]), float(r["chance_jaccard"])))
    fams = [("causal", "Causal (9 configurations)"),
            ("neural", "SHAP (3 architectures)")]
    lines = ["\\begin{table}[htbp]", "\\centering", "\\footnotesize",
             "\\setlength{\\tabcolsep}{3pt}"]
    lines += caption(
        "Cross-method agreement on the attributed variables, as the mean pairwise "
        "Jaccard index over the configurations of each family, beside the agreement two "
        "random selections of the same size would reach. SHAP is computed on "
        "all three datasets, and its three architectures are kept in a group separate "
        "from the nine causal configurations, so that each row measures how far one "
        "family agrees with itself. The two groups differ in size, and the "
        "matched comparison is given in the text. Cls.\\ is the number of anomaly "
        "classes each figure averages over, and it governs how much weight the "
        "comparison bears: the paired test of these differences is reported in "
        "Section~\\ref{sec:attr-intervals}. It separates on industrial at every depth, "
        "where twenty classes stand behind a margin of 0.31 to 0.43; it separates "
        "nowhere on the electrocardiogram, whose largest margin of 0.076 returns "
        "$p = 0.115$; and the robot's three classes cannot reach the 5\\% level at "
        "all, so no verdict is offered there in either direction.",
        "tab:consistency")
    marg, _paired = attribution_ci()
    lines += ["\\begin{tabular}{llrrrrrrr}", "\\toprule",
              "& & & \\multicolumn{2}{c}{Top-3} & \\multicolumn{2}{c}{Top-5} & "
              "\\multicolumn{2}{c}{Top-10}" + NL,
              "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}",
              "Dataset & Family & Cls. & $J$ $\\uparrow$ & Lift $\\uparrow$ & $J$ $\\uparrow$ & Lift $\\uparrow$ & $J$ $\\uparrow$ & Lift $\\uparrow$" + NL,
              "\\midrule"]
    for di, (dom, dlabel) in enumerate(DOMS):
        present = [(f, fl) for f, fl in fams if (dom, f, "3") in by]
        block, ncls = [], ""
        for f, _fl in present:
            cells = []
            for k in ("3", "5", "10"):
                v = by[(dom, f, k)]
                j = sum(x[0] for x in v) / len(v)
                c = sum(x[1] for x in v) / len(v)
                ci = marg.get(("consistency", dom, "top" + k, f))
                ncls = ci["n_classes"] if ci else ncls
                cells += ["%.3f" % j, ("%.1f" % (j / c)) if c else "--"]
            block.append(cells)
        block = bold_best(block, [0, 1, 2, 3, 4, 5])
        for fi, ((f, flabel), cells) in enumerate(zip(present, block)):
            dcell = ("\\multirow{%d}{*}{%s}" % (len(present), dlabel)) if fi == 0 else ""
            ccell = ("\\multirow{%d}{*}{%s}" % (len(present), ncls)) if fi == 0 else ""
            lines.append(dcell + " & " + flabel + " & " + ccell + " & "
                         + " & ".join(cells) + NL)
        if di < len(DOMS) - 1:
            lines.append("\\midrule")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_consistency.tex", lines)


def t_relevance_healthcare():
    """The healthcare classes grouped into the four families the supervisor asked for.

    Pooling all fourteen localisable classes into one number hides the only structure
    in the domain. Infarctions, whose diagnosis is defined by which territory the
    changes appear in, are the one healthcare family the attributions localise above
    chance. Conduction and rhythm classes are at or below it, and for the rhythm group
    that is unsurprising: atrial flutter is not a territorial diagnosis, so the lead
    set it is scored against is a weaker notion of ground truth than the infarction
    territories are.
    """
    groups = [("MI", "Myocardial infarction", 4),
              ("CD", "Conduction disturbance", 4),
              ("HYP", "Hypertrophy", 1),
              ("RHYTHM", "Atrial flutter or fibrillation", 5)]
    by = {}
    for r in read("tools/relevance_by_class.csv"):
        if r["domain"] != "healthcare" or r["rule"] != "top3":
            continue
        by.setdefault((r["group"], r["algorithm"]), []).append(
            (float(r["relevance_pct"]), float(r["chance_pct"])))
    lines = ["\\begin{table}[htbp]", "\\centering", "\\small",
             "\\setlength{\\tabcolsep}{4pt}"]
    lines += caption(
        "Relevance of the top three attributed leads on the healthcare dataset, with the "
        "classes grouped into diagnostic families and not reported one record at a "
        "time. Lift is relative to the share of leads that count as relevant for that "
        "family. The six classes whose diagnosis localises to no particular lead are "
        "excluded, as elsewhere.",
        "tab:relevance-healthcare")
    lines += ["\\begin{tabular}{llrrrrrr}", "\\toprule",
              "& & \\multicolumn{2}{c}{PCMCI} & \\multicolumn{2}{c}{GES} & "
              "\\multicolumn{2}{c}{CAM-UV}" + NL,
              "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
              "Family & Classes & Rel.\\% $\\uparrow$ & Lift $\\uparrow$ & Rel.\\% $\\uparrow$ & Lift $\\uparrow$ & Rel.\\% $\\uparrow$ & Lift $\\uparrow$" + NL,
              "\\midrule"]
    for code, label, n in groups:
        cells = []
        for algo in ("PCMCI", "GES", "CAM-UV"):
            v = by.get((code, algo))
            if not v:
                cells += ["--", "--"]
                continue
            p_ = sum(x[0] for x in v) / len(v)
            c_ = sum(x[1] for x in v) / len(v)
            cells += ["%.1f" % p_, ("%.2f" % (p_ / c_)) if c_ else "--"]
        # Here the algorithms are the columns and the diagnostic families the rows, so
        # the comparison that means anything runs across a row: which algorithm
        # localises this family best. Relevance and lift are ranked separately.
        for group_idx in ([0, 2, 4], [1, 3, 5]):
            vals = []
            for i in group_idx:
                try:
                    vals.append(float(cells[i]))
                except ValueError:
                    vals.append(None)
            live = [v for v in vals if v is not None]
            if not live:
                continue
            top = max(live)
            for i, v in zip(group_idx, vals):
                if v is not None and v == top:
                    cells[i] = BF + cells[i] + "}"
        lines.append(label + " & " + str(n) + " & " + " & ".join(cells) + NL)
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("tbl_relevance_healthcare.tex", lines)


def main():
    os.makedirs(OUT, exist_ok=True)
    print("writing LaTeX tables to Thesis/tables/\n")
    t_main()
    t_domain_detail()
    t_baselines()
    t_bootstrap()
    t_validation()
    t_confounder()
    t_attributions()
    t_shap()
    t_deviation()
    t_density()
    t_lead_ablation()
    t_baseline_parity()
    t_runtime()
    t_parent_cap()
    t_attributions_full()
    t_pc_pcmci()
    t_delong()
    t_relevance()
    t_attr_paired()
    t_attr_paired_full()
    t_consistency()
    t_relevance_healthcare()
    n = len([f for f in os.listdir(OUT) if f.endswith(".tex")])
    print("\n" + str(n) + " tables generated, every figure read from a pipeline CSV.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
